apiVersion: v1
kind: Service
metadata:
  name: boardgame
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000  # Node port range: 30000-32767 (choose within this range)
